dataset:
  root_path: /hpc/projects/intracellular_dashboard/organelle_dynamics
  name: 2024_10_31_A549_SEC61_ZIKV_DENV

processing:
  lf_mask_radius: 0.98
  z_final: 48
  z_window: 20
  z_index: null

fovs:
  beads: C/1/000000
  exclude: null
  include: null

max_drops: null

stages: [1]

overlay_channels:
  - Phase3D
  - raw GFP EX488 EM525-45

annotations_dir: /hpc/projects/intracellular_dashboard/organelle_dynamics/2024_10_31_A549_SEC61_ZIKV_DENV/dynacell/annotations

drop_metrics:
  - blank
  - z_focus
  - manual

qc_thresholds:
  z_focus:
    n_std: 2.5
  beads_registration:
    n_std: 1.0
  laplacian:
    n_std: 1.0
  entropy:
    n_std: 2.5
  hf_ratio:
    n_std: 2.5
  frc:
    n_std: 2.5
  max_intensity:
    n_std: 2.5
  fov_registration:
    n_std: 2.5
  tilt:
    n_std: 2.5

slurm:
  partition: gpu
  cpus_per_task: 4
  mem_per_cpu: 8G
  time: 120
  array_parallelism: 100
