seed_everything: 42
trainer:
  accelerator: gpu
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32-true
  fast_dev_run: false
  enable_progress_bar: true
  inference_mode: true
model:
  class_path: viscy.translation.engine.VSUNet
  init_args:
    architecture: fcmae
    model_config:
      in_channels: 1
      out_channels: 2
      in_stack_depth: 21
      encoder_blocks: [3, 3, 9, 3]
      dims: [96, 192, 384, 768]
      encoder_drop_path_rate: 0.0
      stem_kernel_size: [7, 4, 4]
      in_stack_depth: 21
      decoder_conv_blocks: 2
      pretraining: false
      head_conv: true
      head_conv_expansion_ratio: 4
      head_conv_pool: false
    test_time_augmentations: true
    tta_type: "median"
data:
  class_path: viscy.data.hcs.HCSDataModule
  init_args:
    data_path: /hpc/projects/tlg2/virtual_staining/2024_11_1_zebrafish_she_gfp_cldnb_lyn_mscar_3dpf/1-preprocess/label-free/0-reconstruct/2024_11_01.zarr
    source_channel: Phase3D
    target_channel:
      - "nuclei"
      - "membrane"
    z_window_size: 21
    batch_size: 10
    num_workers: 16
    normalizations:
      - class_path: viscy.transforms.NormalizeSampled
        init_args:
          keys: [Phase3D]
          level: "fov_statistics"
          subtrahend: "median"
          divisor: "iqr"
return_predictions: false
ckpt_path: "/hpc/projects/comp.micro/virtual_staining/models/fcmae-3d/fit_v2/pretrain_end2end/lightning_logs/finetune_VS_end2end_v1_test6_prefetch2_nopersistwork_restart_2/checkpoints/epoch=64-step=24960.ckpt"
