block_size: [64, 64, 32]
blur_kernel_size: 3
nms_distance: 32
min_distance: 50
threshold_abs: 200.0
max_num_peaks: 2000
exclude_border: [5, 10, 5]
device: "cuda"
axis_labels: ["SCAN", "TILT", "COVERSLIP"]
offset: 10  # Offset that will be added to the data
gain: 1000  # Factor by which data will be multiplied after offsetting, useful when working with float data
use_robust_1d_fwhm: false  # Use "robust" 1D FWHM calculation algorithm, usually not needed
fwhm_plot_type: '1D'  # Which data to use in FWHM vs acquisition axis plots, either '1D' or '3D'
