z_slices: [20, 50]
tracking_config:
  segmentation_config:
    min_area: 2100
    max_area: 80000
    n_workers: 10
    min_frontier: 0.4
    max_noise: 0.05
  linking_config:
    n_workers: 10
    max_distance: 15
    distance_weight: -0.0001
    max_neighbors: 3
  tracking_config:
    n_threads: 14
    disappear_weight: -0.0001
    appear_weight: -0.001
    division_weight: -0.0001
functions:
  vs_projection:
    function: np.max
    input_arrays:
      - nuclei_prediction
      - membrane_prediction
    kwargs:
      axis: 1
  preprocessing:
    function: ultrack.imgproc.normalize
    input_arrays:
      - nuclei_prediction
      - membrane_prediction
    kwargs:
      gamma: 0.7
  foreground:
    function: ultrack.imgproc.detect_foreground
    input_arrays:
      - nuclei_prediction
    kwargs:
      sigma: 90
  contourn:
    function: biahub.cli.track.mem_nuc_contour
    input_arrays:
      - nuclei_prediction
      - membrane_prediction
    kwargs: {}
