# Segmentation settings for cellpose
# The model's names will be used for channel names in the output store. (i.e membrane -> membrane_label)
models:
  # One can instantiate as many models
  membrane:
    path_to_model: "/path/to/nucleus/model or name of built-in cellpose model (e.g. cyto3 or nuclei)"
    # These are the common model.CellposeModel().eval() arguments used, but one can add more.
    # For more information, see https://cellpose.readthedocs.io/en/latest/api.html#id0
    eval_args:
      diameter: 65
      channels: ['mem', 'nuc'] #The channel count for Cellpose starts at 1
      cellprob_threshold: 0.4
      invert: false
      do_3D: false   # Optional, if false, 2D segmentation is performed.
      anisotropy: 3.26
      min_size: 8000
    z_slice_2D: 10  # Optional, if null, 3D segmentation is performed and checks eval_args.do_3D=True
    preprocessing:
      - function: skimage.exposure.rescale_intensity  #configurable callables like rescaling intensity
        kwargs: {"out_range": [0, 1]}
        channel: 'mem'
      - function: skimage.exposure.equalize_adapthist
        kwargs: {"clip_limit": 0.01,"kernel_size":[5, 32, 32]}
        channel: 'mem'
  nucleus:
    path_to_model: "/path/to/nucleus/model or name of built-in cellpose model (e.g. cyto3 or nuclei)"
    # These are the common model.CellposeModel().eval() arguments used, but one can add more.
    # For more information, see https://cellpose.readthedocs.io/en/latest/api.html#id0
    eval_args:
      diameter: 60
      channels: ['nuc'] #For nucleus segmentation, only one channel is required. We populate the other channel with zero.
      cellprob_threshold: 0.0
      invert: false
      do_3D: true
      anisotropy: 3.26
      min_size: 8000
    z_slice_2D: null  # Optional, if null, 3D segmentation is performed and checks eval_args.do_3D=True
