direction: pull
moving_channels:
- Phase3D
- Orientation
- Retardance
- Birefringence
reference_channel: GFP
method: beads
transforms:
- matrix:
  - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 1.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 1.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
