# Channel used to estimate stabilization parameters across timepoints.
stabilization_estimation_channel: Phase3D

# List of channels that will be stabilized using the computed transforms.
stabilization_channels:
  - Phase3D

# Type of stabilization to perform
#   - "z" only stabilize in Z
#   - "xy" only stabilize in XY
#   - "xyz" stabilize in all 3D spatial dimensions
stabilization_type: "z"

# Method used to estimate stabilization parameters
#   - "focus-finding" uses intensity-based Z focus to estimate drift in z and use stack-reg to estimate drift in xy
#   - "beads" uses automatically matched beads (only for xyz)
#   - "phase-cross-corr" uses 3D phase correlation (only for xyz)
#   - "ants" uses ANTs registration with optimization (only for xyz)
stabilization_method: "focus-finding"

beads_match_settings:
  algorithm: hungarian # "hungarian", "match_descriptor"
  t_reference: "first" # Reference timepoint for matching
  source_peaks_settings:
    threshold_abs: 110  # intensity threshold for peak detection
    nms_distance: 16    # non-maximum suppression radius
    min_distance: 0     # minimum separation between peaks
    block_size:         # local block size used in detection
      - 8
      - 8
      - 8
  target_peaks_settings:
    threshold_abs: 110  # intensity threshold for peak detection
    nms_distance: 16    # non-maximum suppression radius
    min_distance: 0     # minimum separation between peaks
    block_size:         # local block size used in detection
      - 8
      - 8
      - 8
  match_descriptor_settings:
    distance_metric: euclidean # Distance metric for match descriptor
    max_ratio: 0.8 # Max ratio for match descriptor
    cross_check: True # Cross-check matches
  hungarian_match_settings:
    distance_metric: euclidean # Distance metric for Hungarian algorithm
    cost_threshold: 0.1 # Cost threshold for Hungarian algorithm
    cross_check: True # Cross-check matches
    max_ratio: 0.8 # Max ratio for Hungarian algorithm
    edge_graph_settings:
      method: knn # Method for edge graph
      k: 5 # Number of nearest neighbors
    cost_matrix_settings:
      normalize: False # Normalize cost matrix
      weights: # Weights for cost matrix
        dist: 0.5 # Distance weight
        edge_angle: 1.0 # Edge angle weight
        edge_length: 1.0 # Edge length weight
        pca_dir: 0.0 # Principal Component Analysis direction weight (0.0 means no direction)
        pca_aniso: 0.0 # Principal Component Analysis anisotropy weight (0.0 means no anisotropy)
        edge_descriptor: 0.0 # Edge descriptor weight (0.0 means no descriptor)
  filter_distance_threshold: 0.95 # Filter matches based on distance threshold
  filter_angle_threshold: 0   # Filter matches based on dominant angle direction (in degrees)


phase_cross_corr_settings:
  maximum_shift: 1.2
  normalization: False
  t_reference: "first"

stack_reg_settings:
  crop_size_xy:
    - 800
    - 800
  skip_beads_fov: "0" # FOV index to skip (e.g., bead FOV), as a string
  t_reference: "first"
  focus_finding_settings: # settings for focus finding for Z
    average_across_wells: False    # If True, average focus across all wells
    skip_beads_fov: "0" # FOV index to skip (e.g., bead FOV), as a string
    crop_size_xy: # size of the crop for focus finding
      - 800
      - 800

focus_finding_settings:
  average_across_wells: False # If True, average focus across all wells
  skip_beads_fov: "0" # FOV index to skip (e.g., bead FOV), as a string
  crop_size_xy: # size of the crop for focus finding
    - 800
    - 800

# Settings for affine transformation estimation (applies to all stabilization methods)
affine_transform_settings:
  transform_type: euclidean # Type of transform to estimate "euclidean", "similarity", or "affine"

# Validation and interpolation settings for transform smoothing
eval_transform_settings:
  validation_window_size: 10 # number of timepoints to average over
  validation_tolerance: 1000.0 # max difference between transforms
  interpolation_window_size: 3 # size of the window for interpolation
  interpolation_type: "linear" # "linear" or "cubic"

# Set to True for verbose logging of the stabilization process
verbose: True
