# Name of the fixed (reference) image channel used for registration
target_channel_name: Phase3D

# Name of the moving image channel to align with the target. If using beads, this is the channel with visible beads.
source_channel_name: GFP EX488 EM525-45

# Method to estimate registration parameters:
# "manual": user manually selects matching features
# "beads": automatic detection of bead matches
# "ants": uses ANTs registration with optimization
estimation_method: manual

# Settings used when estimation_method is "beads"
beads_match_settings:
  # Algorithm to match beads between source and target:
  # "hungarian", "match_descriptor", or "mutual_information"
  algorithm: hungarian

  # Only keep matches within this angular threshold (in degrees) of the dominant match orientation
  filter_angle_threshold: 0

  # Max allowed ratio between best and second-best match distances
  max_ratio: 0.8

  # Number of nearest neighbors used to construct bead graphs for matching
  knn_k: 5

  # Whether to perform cross-checking of matches
  cross_check: True

  # Distance metric to use for matching
  distance_metric: euclidean

  # Timepoint reference for matching
  t_reference: "first"

  # Source peaks settings
  source_peaks_settings:
    threshold_abs: 110
    nms_distance: 16
    min_distance: 0
    block_size:
      - 8
      - 8
      - 8
  # Target peaks settings
  target_peaks_settings:
    threshold_abs: 0.8
    nms_distance: 16
    min_distance: 0
    block_size:
      - 8
      - 8
      - 8

# Settings used when estimation_method is "ants"
ants_registration_settings:
  # Whether to apply a Sobel filter for edge enhancement before registration
  sobel_filter: False


# Settings used when estimation_method is "manual"
manual_registration_settings:
  # Timepoint index to use for manual registration
  time_index: 0


  # Number of 90-degree clockwise rotations to apply to source image before registration
  affine_90degree_rotation: 0

# Settings that apply to all methods (manual, beads, ants)
affine_transform_settings:
  # Type of transform to estimate: "euclidean", "similarity", or "affine"
  transform_type: euclidean

  # Optional initial guess for the 4x4 affine transformation matrix
  approx_transform:
  - [1, 0, 0, 0]
  - [0, 0, -1.288, 1960]
  - [0, 1.288, 0, -460]
  - [0.0, 0.0, 0.0, 1.0]

# Post-estimation settings for validating and interpolating affine transforms
eval_transform_settings:
  # Number of timepoints to average over when checking consistency
  validation_window_size: 10

  # Maximum deviation (in pixels) allowed between transformations to be considered valid
  validation_tolerance: 1000.0

  # Number of neighboring timepoints used when interpolating missing transforms
  interpolation_window_size: 3

  # Interpolation method: "linear" or "cubic"
  interpolation_type: "linear"

# If True, print verbose logs during registration and validation
verbose: True
