direction: pull
matrices:
- - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 1.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 1.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
- - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 1.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 1.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
- - - 1.0
    - 0.0
    - 0.0
    - 0.0
  - - 0.0
    - 1.0
    - 0.0
    - 0.0
  - - 0.0
    - 0.0
    - 1.0
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
time_indices: all
source_channels:
- GFP
method: focus-finding
voxel_size:
- 1.0
- 1.0
- 1.0
- 1.0
- 1.0
keep_overhang: false
interpolation: linear
