# Channel used to estimate stabilization parameters across timepoints.
stabilization_estimation_channel: Phase3D

# List of channels that will be stabilized using the computed transforms.
stabilization_channels:
  - Phase3D

# Type of stabilization to perform:
#   - "z": only stabilize in Z
#   - "xy": only stabilize in XY
#   - "xyz": stabilize in all 3D spatial dimensions
stabilization_type: "z"

# Method used to estimate stabilization parameters:
#   - "focus-finding": uses intensity-based Z focus to estimate drift
#   - "beads": uses automatically matched beads (only for xyz)
#   - "phase-cross-corr": uses 3D phase correlation (only for xyz)
stabilization_method: "focus-finding"

# Settings for beads-based stabilization (only used if stabilization_method == "beads")
beads_match_settings: 
  # Matching algorithm to use: "hungarian", "match_descriptor", or "mutual_information"
  algorithm: hungarian

  # Filter matches based on dominant angle direction (in degrees)
  filter_angle_threshold: 0

  # Ratio filter between best and second-best matches (used with descriptors)
  max_ratio: 0.8

  # Number of neighbors used to form bead graphs
  knn_k: 5

  # Whether to enforce symmetric (mutual) matches from both directions
  cross_check: True

  # Distance metric used for descriptor or geometric matching
  distance_metric: euclidean

  # Peak detection settings for the source channel (moving)
  source_peaks_settings:
    threshold_abs: 110  # intensity threshold for peak detection
    nms_distance: 16    # non-maximum suppression radius
    min_distance: 0     # minimum separation between peaks
    block_size:         # local block size used in detection
      - 8
      - 8
      - 8

  # Peak detection settings for the target channel (fixed)
  target_peaks_settings:
    threshold_abs: 110
    nms_distance: 16
    min_distance: 0
    block_size:
      - 8
      - 8
      - 8

  # Temporal reference mode for matching: "first" or "previous"
  t_reference: "first"

# Settings for 3D phase cross-correlation stabilization (only used if stabilization_method == "phase-cross-corr")
phase_cross_corr_settings:
  # Maximum allowed normalized shift (relative to image size)
  maximum_shift: 1.2

  # Whether to normalize magnitude before computing phase correlation
  normalization: False

  # Temporal reference mode for alignment: "first" or "previous"
  t_reference: "first"

# Settings for XY stabilization using image registration (StackReg)
stack_reg_settings:
  # XY crop size (centered region of interest)
  crop_size_xy:
    - 800
    - 800

  # FOV index to skip (e.g., bead FOV), as a string
  skip_beads_fov: "0"

  # Temporal reference for stabilization: "first" or "previous"
  t_reference: "first"

  # Nested Z focus finding settings, used for selecting best Z slice in each timepoint
  focus_finding_settings:
    average_across_wells: False    # If True, average focus across all wells
    skip_beads_fov: "0"
    crop_size_xy:
      - 800
      - 800

# Global settings for Z focus drift estimation
focus_finding_settings:
  average_across_wells: False
  skip_beads_fov: "0"
  crop_size_xy:
    - 800
    - 800

# Settings for affine transformation estimation (applies to all stabilization methods)
affine_transform_settings:
  # Type of transform to estimate: "euclidean", "similarity", or "affine"
  transform_type: euclidean

# Validation and interpolation settings for transform smoothing
eval_transform_settings:
  # Number of timepoints to average over when validating transform stability
  validation_window_size: 10

  # Maximum allowed deviation (in pixels) to consider a transform valid
  validation_tolerance: 1000.0

  # Size of local window used to interpolate missing or invalid transforms
  interpolation_window_size: 3

  # Interpolation method for transform smoothing: "linear" or "cubic"
  interpolation_type: "linear"

# Set to True for verbose logging of the stabilization process
verbose: True
