seed_everything: 42
trainer:
  accelerator: gpu
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32-true
  fast_dev_run: false
  enable_progress_bar: true
  inference_mode: true
model:
  class_path: viscy.translation.engine.VSUNet
  init_args:
    architecture: fcmae
    model_config:
      in_channels: 1
      out_channels: 2
      encoder_blocks: [3, 3, 9, 3]
      dims: [96, 192, 384, 768]
      decoder_conv_blocks: 2
      stem_kernel_size: [5, 4, 4]
      in_stack_depth: 15
      pretraining: false
data:
  class_path: viscy.data.hcs.HCSDataModule
  init_args:
    data_path: /hpc/projects/comp.micro/mantis/2024_05_24_A549_Fig1_redo/5-register/a549_tomm20_lysotracker_w2_2_lf_recon_decon.zarr
    source_channel: Phase3D
    target_channel:
      - "nuclei"
      - "membrane"
    z_window_size: 15
    batch_size: 4
    num_workers: 16
    normalizations:
      - class_path: viscy.transforms.NormalizeSampled
        init_args:
          keys: [Phase3D]
          level: "fov_statistics"
          subtrahend: "median"
          divisor: "iqr"
return_predictions: false
ckpt_path: "/hpc/projects/comp.micro/virtual_staining/models/fcmae-cyto3d-sensor/vscyto3d-logs/hek-a549-ipsc-finetune/checkpoints/epoch=83-step=14532-loss=0.492.ckpt"



